plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
remote_theme: asstart/just-the-docs
baseurl: /obsidian-publish
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  rel_url: true
  button: false
mermaid:
  version: 9.1.3
heading_anchors: true
color_scheme: light
back_to_top: true
back_to_top_text: Back to top
site_footer: This site powered by <a href="https://github.com/just-the-docs/just-the-docs">Just the Docs</a>, a documentation theme for Jekyll and <a href="https://github.com/asstart/obsidian-publish-action">Obsidian Publish Action</a>, a GitHub action for publishing <a href="https://obsidian.md/">Obsidian</a> notes
